[global]
   workgroup = WORKGROUP
   server string = BSL2026 Kiosk
   security = user
   map to guest = Bad User
   guest account = pi
   logging = file
   load printers = no
   disable spoolss = yes

[slideshow]
   path = /home/pi/slideshow
   browseable = yes
   read only = no
   guest ok = yes
   force user = pi
   create mask = 0644
   directory mask = 0755
